# Generated by Django 3.2.7 on 2023-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230714_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
