# Generated by Django 3.2.7 on 2023-07-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clave',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
