# Generated by Django 3.2.7 on 2023-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clave',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
