# Generated by Django 4.2.3 on 2023-08-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_dependencia_user_dp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DP',
            new_name='DP2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombreDependencia',
            new_name='nombreDependencia2',
        ),
    ]
