# Generated by Django 4.2.3 on 2023-08-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_dp2_user_nombredependencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombreDependencia2',
            new_name='DP',
        ),
    ]
