# Generated by Django 4.2.2 on 2023-07-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='image',
            field=models.ImageField(upload_to='dependencias'),
        ),
    ]
