# Generated by Django 4.2.3 on 2023-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0004_alter_dependencia_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='DA',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='DG',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='RM',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='SD',
        ),
        migrations.AddField(
            model_name='dependencia',
            name='dependencia_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='nombreCoordinador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='nombreSecretario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='puestoCoordinador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='puestoSecretario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='DP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='NoUR',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='UR',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='nombreDependencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
