# Generated by Django 3.2.7 on 2023-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noContrato', models.CharField(blank=True, max_length=10, null=True)),
                ('impMensualBruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechaOficio', models.CharField(blank=True, max_length=20, null=True)),
                ('NoOficio', models.CharField(blank=True, max_length=50, null=True)),
                ('nombreSecretario', models.CharField(blank=True, max_length=100, null=True)),
                ('puestoSecretario', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreSecretaria', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreSolicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('puestoSolicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreTestigo', models.CharField(blank=True, max_length=100, null=True)),
                ('puestoTestigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrePdS', models.CharField(blank=True, max_length=100, null=True)),
                ('edadPdS', models.CharField(blank=True, max_length=10, null=True)),
                ('sexoPdS', models.CharField(blank=True, max_length=20, null=True)),
                ('estadoCivilPdS', models.CharField(blank=True, max_length=15, null=True)),
                ('curpdS', models.CharField(blank=True, max_length=20, null=True)),
                ('emailPdS', models.CharField(blank=True, max_length=50, null=True)),
                ('inePdS', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilioPdS', models.CharField(blank=True, max_length=150, null=True)),
                ('rfcPdS', models.CharField(blank=True, max_length=15, null=True)),
                ('statusFirma', models.BooleanField(default=False)),
                ('statusCaptura', models.BooleanField(default=False)),
                ('fechaCreacion', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf1', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('pdf2', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('pdf3', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('pdf4', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('pdf5', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('pdf6', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('pdf7', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('pdf8', models.FileField(blank=True, null=True, upload_to='contratosPDF')),
                ('dependencia_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
