# Generated by Django 3.2.7 on 2023-07-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratosoperativos', '0003_auto_20230718_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratooperativo',
            name='funcionesPsD',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contratooperativo',
            name='montoLetra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
