# Generated by Django 4.2.3 on 2023-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratosoperativos', '0004_auto_20230718_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratooperativo',
            name='fechaFinContrato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contratooperativo',
            name='fechaInicioContrato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
