# Generated by Django 4.2.3 on 2023-08-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratosoperativos', '0010_alter_contratooperativo_pdf1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratooperativo',
            name='puestoTestigo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
