# Generated by Django 4.2.2 on 2023-07-11 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dependencias', '0004_alter_dependencia_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noContrato', models.CharField(max_length=10)),
                ('impMensualBruto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fechaOficio', models.DateField()),
                ('NoOficio', models.CharField(max_length=50)),
                ('nombreSecretario', models.CharField(max_length=100)),
                ('puestoSecretario', models.CharField(max_length=100)),
                ('nombreSecretaria', models.CharField(max_length=100)),
                ('nombreSolicitante', models.CharField(max_length=100)),
                ('puestoSolicitante', models.CharField(max_length=100)),
                ('nombreTestigo', models.CharField(max_length=100)),
                ('puestoTestigo', models.CharField(max_length=100)),
                ('nombrePdS', models.CharField(max_length=100)),
                ('edadPdS', models.CharField(max_length=10)),
                ('sexoPdS', models.CharField(max_length=2)),
                ('estadoCivilPdS', models.CharField(max_length=15)),
                ('curpdS', models.CharField(max_length=20)),
                ('emailPdS', models.CharField(max_length=50)),
                ('inePdS', models.CharField(max_length=20)),
                ('domicilioPdS', models.CharField(max_length=150)),
                ('rfcPdS', models.CharField(max_length=15)),
                ('funcionesProf', models.CharField(max_length=300)),
                ('tituloProf', models.CharField(max_length=50)),
                ('institucionExpTituloProf', models.CharField(max_length=50)),
                ('cedulaProf', models.CharField(max_length=50)),
                ('statusFirma', models.CharField(max_length=2)),
                ('fechaCreacion', models.DateField()),
                ('operativoProf', models.CharField(max_length=50)),
                ('pdf1', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf2', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf3', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf4', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf5', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf6', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf7', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('pdf8', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dependencias.dependencia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
