# Generated by Django 4.2.2 on 2023-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_statuscaptura_alter_contrato_nooficio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fechaCreacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fechaOficio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
