# Generated by Django 4.2.2 on 2023-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='user',
        ),
        migrations.AddField(
            model_name='contrato',
            name='dependencia_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
