# Generated by Django 4.2.2 on 2023-07-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_remove_contrato_dependencia_remove_contrato_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='pdf1',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf2',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf3',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf4',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf5',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf6',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf7',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf8',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='statusCaptura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='statusFirma',
            field=models.BooleanField(default=False),
        ),
    ]
