# Generated by Django 3.2.7 on 2023-07-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_contrato_dependencia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='sexoPdS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='statusCaptura',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='statusFirma',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
