# Generated by Django 3.2.7 on 2023-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_auto_20230713_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='statusCaptura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='statusFirma',
            field=models.BooleanField(default=False),
        ),
    ]
