# Generated by Django 3.2.7 on 2023-07-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_auto_20230713_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='user_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
