# Generated by Django 3.2.7 on 2023-07-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_contrato_user_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='montoLetra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
