# Generated by Django 3.2.7 on 2023-07-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_contrato_montoletra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='montoLetra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='operativoProf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
