# Generated by Django 3.2.7 on 2023-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_auto_20230724_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf2',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf3',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf4',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf5',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf6',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf7',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf8',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
    ]
