# Generated by Django 3.2.7 on 2023-07-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_auto_20230724_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='image',
        ),
        migrations.AddField(
            model_name='contrato',
            name='pdf1',
            field=models.FileField(blank=True, null=True, upload_to='contratosPDF'),
        ),
    ]
