# Generated by Django 4.2.3 on 2023-08-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_alter_contrato_pdf1_alter_contrato_pdf2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='telefonoPdS',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf1',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf2',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf3',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf4',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf5',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf6',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf7',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf8',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
    ]
