# Generated by Django 4.2.3 on 2023-08-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_contrato_telefonopds_alter_contrato_pdf1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='pdf9',
            field=models.FileField(blank=True, null=True, upload_to='documentacionProf'),
        ),
    ]
