# Generated by Django 4.2.3 on 2023-08-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_contrato_pdf9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='pdf1',
            field=models.FileField(blank=True, null=True, upload_to='documentacionPDF'),
        ),
    ]
