# Generated by Django 4.2.3 on 2023-08-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_alter_contrato_pdf1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='funcionesProf',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='puestoSolicitante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='puestoTestigo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
