# Generated by Django 4.2.3 on 2023-08-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0023_alter_contrato_funcionesprof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='institucionExpTituloProf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
