# Generated by Django 4.2.3 on 2023-08-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0024_alter_contrato_institucionexptituloprof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='institucionExpTituloProf',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
