# Generated by Django 4.2.3 on 2023-08-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0025_alter_contrato_institucionexptituloprof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='dependencia_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombreSecretaria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombreSecretario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombreSolicitante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='puestoSecretario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tituloProf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
