# Generated by Django 4.2.3 on 2023-11-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0026_alter_contrato_dependencia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cpPdS',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
