# Generated by Django 4.2.3 on 2023-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0028_contrato_domiciliosecretaria_contrato_nombrevobo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='montoLetraAnterior',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
