name: Deploy master
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Generate Version Label
        id: version_label
        run: echo "::set-output name=version::ver-$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8}"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: reconay-backend
          environment_name: reconay-backend-env
          version_label: ${{ steps.version_label.outputs.version }}
          region: us-east-1
          deployment_package: deploy.zip
        continue-on-error: true

      - name: Notify Deployment Failure
        if: failure()
        run: echo "Deployment failed, consider a rollback or check the error logs"
        # Aquí puedes añadir pasos adicionales para notificaciones o rollback.
